"""empty message

Revision ID: 306265318891
Revises: f4cbc37c8457
Create Date: 2019-04-18 17:09:53.653990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306265318891'
down_revision = 'f4cbc37c8457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('picture_location', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'picture_location')
    # ### end Alembic commands ###
