"""empty message

Revision ID: 7817d973af0d
Revises: 0ea4e58342a2
Create Date: 2019-04-09 10:54:09.850109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7817d973af0d'
down_revision = '0ea4e58342a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('lost_location', sa.String(length=10), nullable=False))
    op.add_column('reports', sa.Column('lost_time', sa.DATETIME(), nullable=False))
    op.add_column('users', sa.Column('user_firstName', sa.String(length=24), nullable=False))
    op.add_column('users', sa.Column('user_lastName', sa.String(length=24), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_lastName')
    op.drop_column('users', 'user_firstName')
    op.drop_column('reports', 'lost_time')
    op.drop_column('reports', 'lost_location')
    # ### end Alembic commands ###
