"""empty message

Revision ID: 93518ea8b6ff
Revises: 3e8d66cc65a1
Create Date: 2019-04-29 10:58:18.690632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93518ea8b6ff'
down_revision = '3e8d66cc65a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('employ_country', sa.String(length=24), nullable=False))
    op.add_column('employees', sa.Column('employ_firstName', sa.String(length=24), nullable=False))
    op.add_column('employees', sa.Column('employ_lastName', sa.String(length=24), nullable=False))
    op.add_column('employees', sa.Column('employ_phone', sa.String(length=24), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'employ_phone')
    op.drop_column('employees', 'employ_lastName')
    op.drop_column('employees', 'employ_firstName')
    op.drop_column('employees', 'employ_country')
    # ### end Alembic commands ###
