"""empty message

Revision ID: a0b64816947e
Revises: c44e79f81237
Create Date: 2019-03-26 14:32:14.486568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0b64816947e'
down_revision = 'c44e79f81237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=24),
               nullable=True)
    op.alter_column('users', 'user_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=24),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=24),
               nullable=False)
    op.alter_column('users', 'user_email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=24),
               nullable=False)
    # ### end Alembic commands ###
