"""empty message

Revision ID: c44e79f81237
Revises: 
Create Date: 2019-03-26 13:48:10.829766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44e79f81237'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employ_email', sa.String(length=24), nullable=False),
    sa.Column('employ_name', sa.String(length=24), nullable=False),
    sa.Column('empliye_password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=24), nullable=False),
    sa.Column('user_name', sa.String(length=24), nullable=False),
    sa.Column('user_password', sa.String(length=100), nullable=False),
    sa.Column('user_phone', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('employees')
    # ### end Alembic commands ###
