"""empty message

Revision ID: c68335be8c41
Revises: fda94c1f436c
Create Date: 2019-04-06 14:47:45.847459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c68335be8c41'
down_revision = 'fda94c1f436c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'employee_feedback',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               nullable=True)
    op.alter_column('reports', 'employee_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('reports', 'report_describe',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'report_describe',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               nullable=False)
    op.alter_column('reports', 'employee_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('reports', 'employee_feedback',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               nullable=False)
    # ### end Alembic commands ###
