"""empty message

Revision ID: ee609d85c1d2
Revises: 38a09e25cfea
Create Date: 2019-04-22 13:27:10.426129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee609d85c1d2'
down_revision = '38a09e25cfea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'picture_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('picture_location', mysql.VARCHAR(collation='utf8mb4_general_ci', length=1000), nullable=True))
    # ### end Alembic commands ###
