"""empty message

Revision ID: f5d6101f885c
Revises: 93518ea8b6ff
Create Date: 2019-04-29 13:18:44.739483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d6101f885c'
down_revision = '93518ea8b6ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_country', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_country')
    # ### end Alembic commands ###
